### ISSUE TITLE
eval with different versions of perl

### ISSUE THREAD

**Issue by pink-mist** [perlbot/perlbuut#10]
It would be great if something like ```5.10eval:```, ```5.12eval:```, ```5.14eval:``` etc would work =)

**Comment by simcop2387** [comment]
thoughts on this from the discussion:

17:26:03 < pink_mist> simcop2387: requesting something like 5.10eval: 5.12eval: 5.14eval: etc :P
17:26:18 < pink_mist> ... I'll make an issue on github =)
17:26:45 < simcop2387> pink_mist: definitely wanting to do it.  gotta figure out a sane way to make it secure against fork bombs since i've got to fork to different perl versions.  though 
                       once i figure that out, i can also add other interpreters easily
17:27:14 < simcop2387> maybe something by allowing exec but locking fork/clone still..
17:27:31 < simcop2387> that'd let someone do exec() in an eval but shouldn't be less secure
17:27:38 < simcop2387> i hope
17:28:22 < pink_mist> =)
17:28:29 < pink_mist> https://github.com/perlbot/perlbuut/issues/10
17:30:00 < Grinnz> sweval5.10
17:30:12 < Grinnz> 5.8evals
17:30:19 < simcop2387> oooo.... i could actually do something really fucked.  i could allow exec but with a specific memory address for the string (looked up just before doing it).
17:30:37 < Grinnz> eval5.24w
17:31:36 < Grinnz> pretty soon simcop2387 is just gonna reinvent travis ci
17:31:38 < simcop2387> it'll be randomized and you won't have a way to look it up.  i think i'd be happy with that.  once i'm done with work today i'll take a look at doing it.  that'd let 
                       me re-add ruby, javscript, and some others in a saner way too
17:31:54 < simcop2387> Grinnz: already done, that's how i rebuild perl blead every morning
17:32:27 < mauke> do you have to go by address? can't you look at the contents?
17:32:47 < simcop2387> no, seccomp doesn't let you do that much introspection, just the values of arguments to system calls
17:32:59 < simcop2387> it's a limitation of the way it's build using eBPF

**Comment by simcop2387** [comment]
this is now supported, 5.5-5.24 + blead.

**Comment by simcop2387** [comment]
This now also supports perl 4 thanks to help from shmem
